#!/bin/bash

UNKNOW=0
UX400_10G=1
UX400_100GE=2
UX400_2P5G=3
UX400_40G=4
UX400_1GE=5
UX400_40GE=6
UX400_16G=7

USB0=1
USB1=2
USB2=3
USB3=4
USB4=5
USB5=6

udport=8030
serverport=8031
DELAY_SD=20
DELAY_SUBBOARD=40
DELAY_MHALT=2

export ifupgrade=0
uret=0

display_dev=/dev/tty7
clear > ${display_dev}
/sbin/ux400cset

echo -e "Copyright (c) 2011-2013 \r" > ${display_dev}
echo -e "                       \r" > ${display_dev}

#echo -e "Module update software version 1.4 \r" > ${display_dev}

/usr/bin/ux400cpldver
cpldver=$?
echo -n "CPLD version: "  > ${display_dev}
echo -n $cpldver > ${display_dev}
echo -e "\r" > ${display_dev}
echo -n "RootFS version: " > ${display_dev}
cat /etc/version > ${display_dev}
echo -e "\r" > ${display_dev}
echo -e "Checking the module boards" > ${display_dev}
echo -e "\r" > ${display_dev}

/sbin/ux400cset

if [ $cpldver -lt 4 ]; then
        /sbin/ux400mod 1
        sleep ${DELAY_SD}
fi

echo -e '\033[9;0]' > ${display_dev}

###################################################################

# 1. slot 2. flag file name
# return: 1: find the module, 0: can't find the module
function modretry()
{
        /sbin/ux400cset

        if [ -f $2 ]; then
                /usr/bin/ux400gpio $1 0
                sleep 2
                /usr/bin/ux400gpio $1 1
                /sbin/ux400cset
                sleep 20
                mtype $1
                machine="$?"
                if [ "$machine" == "$UNKNOW" ]; then
                        /usr/bin/ux400gpio $1 0
                        /sbin/ux400cset
                        sleep 2
                        /usr/bin/ux400gpio $1 1
                        /sbin/ux400cset
                        sleep 20
                        mtype $1
                        machine="$?"
                        if [ "$machine" == "$UNKNOW" ]; then
                                if [ -f $2 ]; then
                                        rm -rf $2
                                fi

                                return 0
                        else
                                return 1
                        fi
                else
                        return 1
                fi
        fi

        return 0
}

#1. USB devices. 2. Module default IP. 3. Module new IP. 4. Module netmask. 5. USB new IP.
function modconfig()
{
        /sbin/ux400cset
        ifconfig $1 192.168.250.8 up
        if [ $? -ne 0 ]; then
                return 1
        fi
        ping $2 -c 1
        if [ $? -ne 0 ]; then
                ifconfig $1 down
                return 1
        fi
        /sbin/ux400cset
        /usr/bin/setip $2 $3 $4
        ifconfig $1 $5 netmask $4 up
        ping $3 -c 1
        if [ $? -ne 0 ]; then
                ifconfig $1 down
                return 1
        fi
        /sbin/ux400cset
        /usr/bin/setdate $3 > /resv/v400/$3
        return 0
}

sdup="0"

function configip()
{
        mdevcheck $1
        usbdev="$?"
	if [ "$usbdev" == "$USB0" ]; then
		modconfig usb0 192.168.250.2 128.0.0.2 255.255.255.252 128.0.0.1
		if [ $? -ne 0 ]; then
			/usr/bin/ux400gpio $1 0
			sleep ${DELAY_MHALT}
			/usr/bin/ux400gpio $1 1
			sleep ${DELAY_SUBBOARD}
			modconfig usb0 192.168.250.2 128.0.0.2 255.255.255.252 128.0.0.1
			if [ $? -ne 0 ]; then
				/sbin/ux400cset
				ifconfig usb0 down
				echo -e "Can't connect to usb0\r" > ${display_dev}
				sleep 60
				return 3
			fi
		fi
		if [ -f /resv/v400/usb0sdup.log ]; then
			grep -r "SUCCESS" /resv/v400/usb0sdup.log
			sdup="$?"
		fi
        elif [ "$usbdev" == "$USB1" ]; then
                modconfig usb1 192.168.250.2 128.0.0.6 255.255.255.252 128.0.0.5
		if [ $? -ne 0 ]; then
                        /usr/bin/ux400gpio $1 0
                        sleep ${DELAY_MHALT}
                        /usr/bin/ux400gpio $1 1
                        sleep ${DELAY_SUBBOARD}
			modconfig usb1 192.168.250.2 128.0.0.6 255.255.255.252 128.0.0.5
			if [ $? -ne 0 ]; then
				ifconfig usb1 down
				echo -e "Can't connect to usb1\r" > ${display_dev}
                                sleep 60
				return 3
			fi
		fi
		if [ -f /resv/v400/usb1sdup.log ]; then
			grep -r "SUCCESS" /resv/v400/usb1sdup.log
			sdup="$?"
		fi
        elif [ "$usbdev" == "$USB2" ]; then
                modconfig usb2 192.168.250.2 128.0.0.10 255.255.255.252 128.0.0.9
		if [ $? -ne 0 ]; then
                        /usr/bin/ux400gpio $1 0
                        sleep ${DELAY_MHALT}
                        /usr/bin/ux400gpio $1 1
                        sleep ${DELAY_SUBBOARD}
			modconfig usb2 192.168.250.2 128.0.0.10 255.255.255.252 128.0.0.9
                        if [ $? -ne 0 ]; then
				/sbin/ux400cset
				ifconfig usb2 down
                                echo -e "Can't connect to usb2\r" > ${display_dev}
                                sleep 60
                                return 3
                        fi
		fi
		if [ -f /resv/v400/usb2sdup.log ]; then
			grep -r "SUCCESS" /resv/v400/usb2sdup.log
			sdup="$?"
		fi
        elif [ "$usbdev" == "$USB3" ]; then
                modconfig usb3 192.168.250.2 128.0.0.14 255.255.255.252 128.0.0.13
		if [ $? -ne 0 ]; then
                        /usr/bin/ux400gpio $1 0
                        sleep ${DELAY_MHALT}
                        /usr/bin/ux400gpio $1 1
                        sleep ${DELAY_SUBBOARD}
			modconfig usb3 192.168.250.2 128.0.0.14 255.255.255.252 128.0.0.13
                        if [ $? -ne 0 ]; then
				/sbin/ux400cset
				ifconfig usb3 down
                                echo -e "Can't connect to usb3\r" > ${display_dev}
                                sleep 60
                                return 3
                        fi
		fi
		if [ -f /resv/v400/usb3sdup.log ]; then
			grep -r "SUCCESS" /resv/v400/usb3sdup.log
			sdup="$?"
		fi
        elif [ "$usbdev" == "$USB4" ]; then
                modconfig usb4 192.168.250.2 128.0.0.18 255.255.255.252 128.0.0.17
		if [ $? -ne 0 ]; then
                        /usr/bin/ux400gpio $1 0
                        sleep ${DELAY_MHALT}
                        /usr/bin/ux400gpio $1 1
                        sleep ${DELAY_SUBBOARD}
			modconfig usb4 192.168.250.2 128.0.0.18 255.255.255.252 128.0.0.17
                        if [ $? -ne 0 ]; then
				/sbin/ux400cset
				ifconfig usb4 down
                                echo -e "Can't connect to usb4\r" > ${display_dev}
                                sleep 60
                                return 3
                        fi
		fi
		if [ -f /resv/v400/usb4sdup.log ]; then
			grep -r "SUCCESS" /resv/v400/usb4sdup.log
			sdup="$?"
		fi
        elif [ "$usbdev" == "$USB5" ]; then
                modconfig usb5 192.168.250.2 128.0.0.22 255.255.255.252 128.0.0.21
		if [ $? -ne 0 ]; then
                        /usr/bin/ux400gpio $1 0
                        sleep ${DELAY_MHALT}
                        /usr/bin/ux400gpio $1 1
                        sleep ${DELAY_SUBBOARD}
			modconfig usb5 192.168.250.2 128.0.0.22 255.255.255.252 128.0.0.21
                        if [ $? -ne 0 ]; then
				/sbin/ux400cset
				ifconfig usb5 down
                                echo -e "Can't connect to usb5\r" > ${display_dev}
                                sleep 60
                                return 3
                        fi
		fi
		if [ -f /resv/v400/usb5sdup.log ]; then
			grep -r "SUCCESS" /resv/v400/usb5sdup.log
			sdup="$?"
		fi
	else
#		echo -e "Unsupport USB device" > ${display_dev}
		return 0
        fi

}

#slots
function mupgrade()
{

	/sbin/ux400cset
	bucheck $1
	update="$?"
	echo -ne "    \r" > ${display_dev}


	if [ $update -eq 0 ]; then
		if [ $sdup -eq 0 ]; then
			return 0
		else
			echo "$1: SD card need upgrade" > ${display_dev}
		fi
	fi
	
	mtype $1
	machine="$?"

	rm -rf /resv/v400/ux400-module-sd.tar.gz

	if [ "$machine" == "$UX400_10G" ]; then
		if [ -f /usr/local/10g/share/ux400-module-10g.tar.gz ]; then
			imagename="ux400-module-10g.tar.gz"
			machinename="10G"
			boardname="10g"
			rm -rf /resv/v400/ux400-module-10g.tar.gz
			ln -s /usr/local/10g/share/ux400-module-10g.tar.gz /resv/v400/ux400-module-10g.tar.gz
			if [ -f /usr/local/10g/share/ux400-module-sd.tar.gz ]; then
				ln -s /usr/local/10g/share/ux400-module-sd.tar.gz /resv/v400/ux400-module-sd.tar.gz
			fi
		else
			echo -n "Can't find the software for board" > ${display_dev}
			echo -n $imagename > ${display_dev}
			echo -n "in slot" > ${display_dev}
			echo $1
			/sbin/ux400cset
			return 2
		fi
	elif [ "$machine" == "$UX400_100GE" ]; then
		if [ -f /usr/local/100ge/share/ux400-module-100ge.tar.gz ]; then
			imagename="ux400-module-100ge.tar.gz"
			machinename="100GE"
			boardname="100ge"
			rm -rf /resv/v400/ux400-module-100ge.tar.gz
			ln -s /usr/local/100ge/share/ux400-module-100ge.tar.gz /resv/v400/ux400-module-100ge.tar.gz
			
                        if [ -f /usr/local/100ge/share/ux400-module-sd.tar.gz ]; then
                                ln -s /usr/local/100ge/share/ux400-module-sd.tar.gz /resv/v400/ux400-module-sd.tar.gz
                        fi
		else
			echo -n "Can't find the software for board" > ${display_dev}
			echo -n $imagename > ${display_dev}
			echo -n "in slot" > ${display_dev}
			echo $1
			/sbin/ux400cset
			return 2
		fi
	elif [ "$machine" == "$UX400_2P5G" ]; then
		if [ -f /usr/local/2p5g/share/ux400-module-2p5g.tar.gz ]; then
			imagename="ux400-module-2p5g.tar.gz"
			machinename="2.5G"
			boardname="2p5g"
			rm -rf /resv/v400/ux400-module-2p5g.tar.gz
			ln -s /usr/local/2p5g/share/ux400-module-2p5g.tar.gz /resv/v400/ux400-module-2p5g.tar.gz
		else
			echo -n "Don't need upgrade module software for board" > ${display_dev}
			echo -n $imagename > ${display_dev}
			echo -n "in slot" > ${display_dev}
			echo $1
			/sbin/ux400cset
			return 2
		fi
	elif [ "$machine" == "$UX400_1GE" ]; then
		if [ -f /usr/local/1ge/share/ux400-module-1ge.tar.gz ]; then
			imagename="ux400-module-1ge.tar.gz"
			machinename="1GE"
			boardname="1ge"
			rm -rf /resv/v400/ux400-module-1ge.tar.gz
			ln -s /usr/local/1ge/share/ux400-module-1ge.tar.gz /resv/v400/ux400-module-1ge.tar.gz
                        if [ -f /usr/local/1ge/share/ux400-module-sd.tar.gz ]; then
                                ln -s /usr/local/1ge/share/ux400-module-sd.tar.gz /resv/v400/ux400-module-sd.tar.gz
                        fi
		else
			echo -n "Can't find the software for board" > ${display_dev}
			echo -n $imagename > ${display_dev}
			echo -n "in slot" > ${display_dev}
			echo $1
			/sbin/ux400cset
			return 2
		fi
	elif [ "$machine" == "$UX400_40GE" ]; then
		if [ -f /usr/local/40ge/share/ux400-module-40ge.tar.gz ]; then
			imagename="ux400-module-40ge.tar.gz"
			machinename="40GE"
			boardname="40ge"
			rm -rf /resv/v400/ux400-module-40ge.tar.gz
			ln -s /usr/local/40ge/share/ux400-module-40ge.tar.gz /resv/v400/ux400-module-40ge.tar.gz
                        if [ -f /usr/local/40ge/share/ux400-module-sd.tar.gz ]; then
                                ln -s /usr/local/40ge/share/ux400-module-sd.tar.gz /resv/v400/ux400-module-sd.tar.gz
                        fi
		else
			echo -n "Can't find the software for board" > ${display_dev}
			echo -n $imagename > ${display_dev}
			echo -n "in slot" > ${display_dev}
			echo $1
			/sbin/ux400cset
			return 2
		fi
        elif [ "$machine" == "$UX400_40G" ]; then
                if [ -f /usr/local/40g/share/ux400-module-40g.tar.gz ]; then
                        imagename="ux400-module-40g.tar.gz"
                        machinename="40G"
			boardname="40g"
                        rm -rf /resv/v400/ux400-module-40g.tar.gz
                        ln -s /usr/local/2p5g/share/ux400-module-40g.tar.gz /resv/v400/ux400-module-40g.tar.gz
                else
                        echo -n "Don't need upgrade module software for board" > ${display_dev}
                        echo -n $imagename > ${display_dev}
                        echo -n "in slot" > ${display_dev}
                        echo $1
                        /sbin/ux400cset
                        return 2
                fi
        elif [ "$machine" == "$UX400_16G" ]; then
                if [ -f /usr/local/16g/share/ux400-module-16g.tar.gz ]; then
                        imagename="ux400-module-16g.tar.gz"
                        machinename="16G"
			boardname="16g"
                        rm -rf /resv/v400/ux400-module-16g.tar.gz
                        ln -s /usr/local/16g/share/ux400-module-16g.tar.gz /resv/v400/ux400-module-16g.tar.gz
                else
                        echo -n "Don't need upgrade module software for board" > ${display_dev}
                        echo -n $imagename > ${display_dev}
                        echo -n "in slot" > ${display_dev}
                        echo $1
                        /sbin/ux400cset
                        return 2
                fi
	else
		echo -n "Unsupport machine" > ${display_dev}
		echo -r "\r" > ${display_dev}
		return 3
	fi

	echo -e $imagename

        cp -rf /usr/bin/mdarms /resv/v400/
        cp -rf /usr/bin/kill-mods /resv/v400/
	cp -rf /usr/bin/ud /resv/v400/
	cp -rf /usr/bin/arm/mke2fs /resv/v400/
	cp -rf /usr/bin/arm/parted.sh /resv/v400/
	cp -rf /usr/bin/arm/veextmp.ko /resv/v400/

        chown v400:v400 /resv/v400/*
	
	/sbin/ux400cset
	mdevcheck $1
	usbdev="$?"
	locate=$1
	/sbin/ux400cset
	ifconfig eth0 up

	if [ "$usbdev" == "$USB0" ]; then
		rm -rf /resv/v400/usb0fup.log
		ping 128.0.0.2 -c 1
		if [ $? -ne 0 ]; then
			ifconfig usb0 192.168.250.3  up
			modconfig usb0 192.168.250.2 128.0.0.2 255.255.255.252 128.0.0.1
		fi

		/usr/bin/modud 128.0.0.2 128.0.0.1 $udport
		#/usr/bin/modup 128.0.0.2 128.0.0.1 $imagename > /resv/v400/usb0fup.log
		sleep 5
		/usr/bin/client 128.0.0.2 $udport 128.0.0.1 $imagename $boardname /resv/v400/usb0fup.log $locate > ${display_dev}
		grep -r "SUCCESS" /resv/v400/usb0fup.log
	  	if [ $? -ne 0 ]; then
			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
			/sbin/ux400cset
			return 3
	 	else
                        #if [ -f /resv/v400/ux400-module-sd.tar.gz ]; then
		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
				echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
				rm -rf /resv/v400/usb0sdup.log
	                        sleep ${DELAY_SD}
				/usr/bin/client 128.0.0.2 $udport 128.0.0.1 ux400-module-sd.tar.gz $boardname /resv/v400/usb0sdup.log $locate > ${display_dev}
                	        if [ $? -ne 0 ]; then
					/usr/bin/sdupfail > ${display_dev}
					sleep 1
					halt
					return 0
                	        fi
	                fi

			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade success\r" > ${display_dev}
			/usr/bin/modoff 128.0.0.2
			/sbin/ux400cset
			return 1
	  	fi
	elif [ "$usbdev" == "$USB1" ]; then
		rm -rf /resv/v400/usb1fup.log
                ping 128.0.0.6 -c 1
                if [ $? -ne 0 ]; then
			ifconfig usb1 192.168.250.3 up
			modconfig usb1 192.168.250.2 128.0.0.6 255.255.255.252 128.0.0.5
                fi

		/usr/bin/modud 128.0.0.6 128.0.0.5 $udport
		#/usr/bin/modup 128.0.0.6 128.0.0.5 $imagename > /resv/v400/usb1fup.log
		sleep 5
		/usr/bin/client 128.0.0.6 $udport 128.0.0.5 $imagename $boardname /resv/v400/usb1fup.log $locate > ${display_dev}
		grep -r "SUCCESS" /resv/v400/usb1fup.log
	  	if [ $? -ne 0 ]; then
			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
			return 3
			/sbin/ux400cset
	  	else
                        #if [ -f /resv/v400/ux400-module-sd.tar.gz ]; then
		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
				rm -rf /resv/v400/usb1sdup.log
                                sleep ${DELAY_SD}
                                /usr/bin/client 128.0.0.6 $udport 128.0.0.5 ux400-module-sd.tar.gz $boardname /resv/v400/usb1sdup.log $locate > ${display_dev}
                                if [ $? -ne 0 ]; then
					/usr/bin/sdupfail > ${display_dev}
					sleep 1
					halt
					return 0
				fi
                        fi

			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade success\r" > ${display_dev}
			/sbin/ux400cset
			/usr/bin/modoff 128.0.0.6
			return 1
	  	fi
	elif [ "$usbdev" == "$USB2" ]; then
		rm -rf /resv/v400/usb2fup.log
                ping 128.0.0.10 -c 1
                if [ $? -ne 0 ]; then
			ifconfig usb2 192.168.250.3 up
			modconfig usb2 192.168.250.2 128.0.0.10 255.255.255.252 128.0.0.9
                fi

		/usr/bin/modud 128.0.0.10 128.0.0.9 $udport
		#/usr/bin/modup 128.0.0.10 128.0.0.9 $imagename > /resv/v400/usb2fup.log
		sleep 5
		/usr/bin/client 128.0.0.10 $udport 128.0.0.9 $imagename $boardname /resv/v400/usb2fup.log $locate > ${display_dev}
		grep -r "SUCCESS" /resv/v400/usb2fup.log
	  	if [ $? -ne 0 ]; then
			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
			/sbin/ux400cset
			return 3
	  	else
                        #if [ -f /resv/v400/ux400-module-sd.tar.gz ]; then
		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
				rm -rf /resv/v400/usb2sdup.log
                                sleep ${DELAY_SD}
                                /usr/bin/client 128.0.0.10 $udport 128.0.0.9 ux400-module-sd.tar.gz $boardname /resv/v400/usb2sdup.log $locate > ${display_dev}
                                if [ $? -ne 0 ]; then
					/usr/bin/sdupfail > ${display_dev}
					sleep 1
					halt
					return 0
                                fi
                        fi

			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade success\r" > ${display_dev}
			/usr/bin/modoff 128.0.0.10
			/sbin/ux400cset
			return 1
	  	fi
	elif [ "$usbdev" == "$USB3" ]; then
		rm -rf /resv/v400/usb3fup.log
                ping 128.0.0.14 -c 1
                if [ $? -ne 0 ]; then
			ifconfig usb3 192.168.250.3 up
			modconfig usb3 192.168.250.2 128.0.0.14 255.255.255.252 128.0.0.13
                fi

		/usr/bin/modud 128.0.0.14 128.0.0.13 $udport
		#/usr/bin/modup 128.0.0.14 128.0.0.13 $imagename > /resv/v400/usb3fup.log
		sleep 5
		/usr/bin/client 128.0.0.14 $udport 128.0.0.13 $imagename $boardname /resv/v400/usb3fup.log $locate > ${display_dev}
		grep -r "SUCCESS" /resv/v400/usb3fup.log
		if [ $? -ne 0 ]; then
			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
			/sbin/ux400cset
			return 3
	  	else
                        #if [ -f /resv/v400/ux400-module-sd.tar.gz ]; then
		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
				rm -rf /resv/v400/usb3sdup.log
                                sleep ${DELAY_SD}
                                /usr/bin/client 128.0.0.14 $udport 128.0.0.13 ux400-module-sd.tar.gz $boardname /resv/v400/usb3sdup.log $locate > ${display_dev}
                                if [ $? -ne 0 ]; then
					/usr/bin/sdupfail > ${display_dev}
					sleep 1
					halt
					return 0
				fi
                        fi

			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade success\r" > ${display_dev}
			/usr/bin/modoff 128.0.0.14
			/sbin/ux400cset
			return 1
	  	fi
	elif [ "$usbdev" == "$USB4" ]; then
		rm -rf /resv/v400/usb4fup.log
                ping 128.0.0.18 -c 1
                if [ $? -ne 0 ]; then
			ifconfig usb4 192.168.250.3 up
			modconfig usb4 192.168.250.2 128.0.0.18 255.255.255.252 128.0.0.17
                fi

		/usr/bin/modud 128.0.0.18 128.0.0.17 $udport
		#/usr/bin/modup 128.0.0.18 128.0.0.17 $imagename > /resv/v400/usb4fup.log
		sleep 5
		/usr/bin/client 128.0.0.18 $udport 128.0.0.17 $imagename $bardname /resv/v400/usb4fup.log $locate > ${display_dev}
		grep -r "SUCCESS" /resv/v400/usb4fup.log
	  	if [ $? -ne 0 ]; then
			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
			/sbin/ux400cset
			return 3
	  	else
                        #if [ -f /resv/v400/ux400-module-sd.tar.gz ]; then
		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
				rm -rf /resv/v400/usb4sdup.log
                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
                                sleep ${DELAY_SD}
                                /usr/bin/client 128.0.0.18 $udport 128.0.0.17 ux400-module-sd.tar.gz $boardname /resv/v400/usb4sdup.log $locate > ${display_dev}
                                if [ $? -ne 0 ]; then
					/usr/bin/sdupfail > ${display_dev}
					sleep 1
					halt
					return 0
                                fi
                        fi

			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade success\r" > ${display_dev}
			/usr/bin/modoff 128.0.0.18
			/sbin/ux400cset
			return 1
	  	fi
	elif [ "$usbdev" == "$USB5" ]; then
		rm -rf /resv/v400/usb5fup.log
                ping 128.0.0.22 -c 1
                if [ $? -ne 0 ]; then
			ifconfig usb5 192.168.250.3 up
			modconfig usb5 192.168.250.2 128.0.0.22 255.255.255.252 128.0.0.21
                fi
		/usr/bin/modud 128.0.0.22 128.0.0.21 $udport
		#/usr/bin/modup 128.0.0.22 128.0.0.21 $imagename > /resv/v400/usb5fup.log
		sleep 5
		/usr/bin/client 128.0.0.22 $udport 128.0.0.21 $imagename $boardname /resv/v400/usb5fup.log $locate > ${display_dev}
		grep -r "SUCCESS" /resv/v400/usb5fup.log
	  	if [ $? -ne 0 ]; then
			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
			/sbin/ux400cset
			return 3
	  	else
                        #if [ -f /resv/v400/ux400-module-sd.tar.gz ]; then
		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
				rm -rf /resv/v400/usb5sdup.log
                                sleep ${DELAY_SD}
                                /usr/bin/client 128.0.0.22 $udport 128.0.0.21 ux400-module-sd.tar.gz $boardname /resv/v400/usb5sdup.log $locate > ${display_dev} 
                                if [ $? -ne 0 ]; then
					/usr/bin/sdupfail > ${display_dev}
					sleep 1
					halt
					return 0
                                fi
                        fi

			echo -n "The " > ${display_dev}
			echo -n $machinename > ${display_dev}
			echo -n " module in slot " > ${display_dev}
			echo -n "$1" > ${display_dev}
			echo -e " upgrade success\r" > ${display_dev}
			/usr/bin/modoff 128.0.0.22
			/sbin/ux400cset
			return 1
	  	fi
	else
		echo "Unsupport USB device"
	fi
}


function multiup()
{
	mtype $1
	machine="$?"
	if [ "$machine" == "$UNKNOW" ]; then
	        echo -e "Can't find module board at slot $1\r"

	        sleep 1
	        mtype $1
	        machine="$?"
	        if [ "$machine" == "$UNKNOW" ]; then
	                modretry $1 /resv/v400/$1
	                modret="$?"
	                if [ $modret -eq 1 ]; then
	                        mupgrade $1
	                        uret="$?"
	                        touch /resv/v400/$1
	                fi
	        else
	                mupgrade $1
	                uret="$?"
	                touch /resv/v400/$1
	        fi
	else
	        mupgrade $1
	        uret="$?"
	        touch /resv/v400/$1
	fi
	return $uret
}

###################################################################


start vsftpd

ifconfig usb0 down
ifconfig usb1 down
ifconfig usb2 down
ifconfig usb3 down
ifconfig usb4 down
ifconfig usb5 down

slot_arr=("LA" "LB" "LC" "RA" "RB" "RC")

for location in ${slot_arr[@]}
do
	configip $location

done


for location in ${slot_arr[@]}
do
	multiup $location &

done

for pid in $(jobs -p)
do
	wait $pid
	retval=$?

	if [ $retval -gt $ifupgrade ]; then
		ifupgrade=$retval
	fi
done

if [ $ifupgrade -gt 2 ]; then
        ux400buzz 1
        sleep 0.3
        ux400buzz 0
        sleep 0.3
        ux400buzz 1
        sleep 0.3
        ux400buzz 0
        sleep 0.3
        ux400buzz 1
        sleep 0.3
        ux400buzz 0
        sleep 10
        halt
fi

if [ $ifupgrade -gt 0 ]; then
        echo -e "Upgrade finished, halt\r" > ${display_dev}
        ux400buzz 1
        sleep 0.3
        ux400buzz 0

        sleep 3
        halt
fi

